# Generated by Django 4.1.5 on 2023-02-20 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment", name="email", field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="comment", name="name", field=models.CharField(max_length=100),
        ),
    ]
