# Generated by Django 4.1.5 on 2023-02-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_comment_created_at_alter_comment_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, upload_to="comments/"),
        ),
    ]
